### PR TITLE
Update es_es.json

### PR DESCRIPTION
**Pull request by albertosaurio65**

### CODE REVIEW

**Comment by Dark-Arcana** [comment]
The only difference in this commit is that it adds a space after a comma. Check the "files changed" diff to see what I mean. Please try again. You will get the hang of it, I promise. But I can't accept an empty PR.

**Comment by albertosaurio65** [comment]
The real change was in the previous one, you told me to upload it as another branch and for that I had to modify it 🙄 so i put the space for him to leave me, not by choice, the change i made was that i was missing two letters in two words

**Comment by Dark-Arcana** [comment]
I understand. But when you created a new branch, it did not contain the changes you had made before. Check the commits and files changed. It will show the difference between your PR branch and the branch you are trying to merge into. It does not show the difference from those two words from before. If you would like, just tell me what you wanted changed here and I will add it into my next update, no PR needed.

**Comment by albertosaurio65** [comment]
i uploaded one before i read this
`  "alchemistry.container.lock_recipe": "Bloquear receta",`
`"alchemistry.container.unlock_recipe": "Desbloquear receta",`

**Pull request closed without merging**
